"""roles

Revision ID: 002707736dc5
Revises: 88a1f159cea9
Create Date: 2021-01-16 16:43:11.214368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002707736dc5'
down_revision = '88a1f159cea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('roles', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'roles')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
