"""roles update

Revision ID: 0a053ce243e2
Revises: 002707736dc5
Create Date: 2021-01-16 17:43:29.653330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a053ce243e2'
down_revision = '002707736dc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.String(length=10), nullable=True))
    op.drop_column('user', 'roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('roles', sa.VARCHAR(length=10), nullable=True))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
