"""oldest_risk_date

Revision ID: 17ca28bd2bf8
Revises: 002707736dc5
Create Date: 2021-01-18 10:12:07.434211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17ca28bd2bf8'
down_revision = '002707736dc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('oldest_risk_date', sa.BigInteger(), nullable=True))
    op.drop_column('user', 'roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('roles', sa.VARCHAR(length=10), nullable=True))
    op.drop_column('user', 'oldest_risk_date')
    # ### end Alembic commands ###
