"""tables

Revision ID: 73db69fdbbf0
Revises: aea3ddd19df5
Create Date: 2021-01-08 11:22:49.529637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73db69fdbbf0'
down_revision = 'aea3ddd19df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('positive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'positive')
    # ### end Alembic commands ###
