"""add test_date in users table

Revision ID: 88a1f159cea9
Revises: 257c76914c0a
Create Date: 2021-01-09 19:00:59.749843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a1f159cea9'
down_revision = '257c76914c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test_date', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'test_date')
    # ### end Alembic commands ###
