"""tables

Revision ID: aea3ddd19df5
Revises: 2315e7c70bc3
Create Date: 2021-01-08 11:21:07.756816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aea3ddd19df5'
down_revision = '2315e7c70bc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db',
    sa.Column('prob', sa.Float(), nullable=True),
    sa.Column('start', sa.BigInteger(), nullable=False),
    sa.Column('lat', sa.BigInteger(), nullable=True),
    sa.Column('long', sa.BigInteger(), nullable=True),
    sa.Column('finish', sa.BigInteger(), nullable=True),
    sa.Column('placeId', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('start', 'placeId')
    )
    op.create_index(op.f('ix_db_finish'), 'db', ['finish'], unique=False)
    op.create_index(op.f('ix_db_lat'), 'db', ['lat'], unique=False)
    op.create_index(op.f('ix_db_long'), 'db', ['long'], unique=False)
    op.create_index(op.f('ix_db_prob'), 'db', ['prob'], unique=False)
    op.create_table('place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.BigInteger(), nullable=False),
    sa.Column('lat', sa.BigInteger(), nullable=True),
    sa.Column('long', sa.BigInteger(), nullable=True),
    sa.Column('finish', sa.BigInteger(), nullable=True),
    sa.Column('placeId', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'start')
    )
    op.create_index(op.f('ix_place_finish'), 'place', ['finish'], unique=False)
    op.create_index(op.f('ix_place_lat'), 'place', ['lat'], unique=False)
    op.create_index(op.f('ix_place_long'), 'place', ['long'], unique=False)
    op.create_index(op.f('ix_place_placeId'), 'place', ['placeId'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_place_placeId'), table_name='place')
    op.drop_index(op.f('ix_place_long'), table_name='place')
    op.drop_index(op.f('ix_place_lat'), table_name='place')
    op.drop_index(op.f('ix_place_finish'), table_name='place')
    op.drop_table('place')
    op.drop_index(op.f('ix_db_prob'), table_name='db')
    op.drop_index(op.f('ix_db_long'), table_name='db')
    op.drop_index(op.f('ix_db_lat'), table_name='db')
    op.drop_index(op.f('ix_db_finish'), table_name='db')
    op.drop_table('db')
    # ### end Alembic commands ###
